#!/usr/bin/env bash
# Wrap pending migrations in ONE transaction for the Supabase SQL editor
# (production has no migration tracking table; see "Production database
# changes" in docs/ai-agents/LESSONS_LEARNED.md). Usage:
#   scripts/db/prod-bundle.sh 00035 > scripts/db/prod/apply-00035.sql
# Regenerate whenever a bundled migration changes. Never run it against prod
# from here: the operator pastes the output into the dashboard.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
[ $# -ge 1 ] || { echo "usage: $0 <migration number>..." >&2; exit 2; }
cat <<'HDR'
-- Generated by scripts/db/prod-bundle.sh; do not edit by hand.
-- Paste into the Supabase SQL editor and run once. All or nothing: any error
-- rolls the whole file back and leaves production unchanged.
BEGIN;

-- Preconditions: main's schema through 00034 is in place.
DO $$
BEGIN
  IF to_regclass('public.profile_visitors') IS NULL OR to_regclass('public.conversion_events') IS NULL THEN
    RAISE EXCEPTION 'migration 00024 (attribution foundation) is not applied';
  END IF;
  IF to_regclass('public.stripe_events') IS NULL OR to_regprocedure('public.fulfill_stripe_checkout(text,text,jsonb)') IS NULL THEN
    RAISE EXCEPTION 'migration 00031 (payments integrity) is not applied';
  END IF;
  IF to_regclass('public.seat_holds') IS NULL THEN
    RAISE EXCEPTION 'migration 00033 (seat holds) is not applied';
  END IF;
  -- 00035 adds a unique index on analytics_sessions (studio_id, visitor_id, session_token).
  IF EXISTS (SELECT 1 FROM analytics_sessions GROUP BY studio_id, visitor_id, session_token HAVING count(*) > 1) THEN
    RAISE EXCEPTION 'duplicate analytics_sessions visits exist; clean them up before applying 00035';
  END IF;
END $$;
HDR
for n in "$@"; do
  f=$(ls "$ROOT"/supabase/migrations/"${n}"_*.sql)
  printf '\n-- ===== %s =====\n' "$(basename "$f")"
  cat "$f"
done
printf '\nCOMMIT;\n'
