-- Generated by scripts/db/prod-bundle.sh; do not edit by hand.
-- Paste into the Supabase SQL editor and run once. All or nothing: any error
-- rolls the whole file back and leaves production unchanged.
BEGIN;

-- Preconditions: main's schema through 00034 is in place.
DO $$
BEGIN
  IF to_regclass('public.profile_visitors') IS NULL OR to_regclass('public.conversion_events') IS NULL THEN
    RAISE EXCEPTION 'migration 00024 (attribution foundation) is not applied';
  END IF;
  IF to_regclass('public.stripe_events') IS NULL OR to_regprocedure('public.fulfill_stripe_checkout(text,text,jsonb)') IS NULL THEN
    RAISE EXCEPTION 'migration 00031 (payments integrity) is not applied';
  END IF;
  IF to_regclass('public.seat_holds') IS NULL THEN
    RAISE EXCEPTION 'migration 00033 (seat holds) is not applied';
  END IF;
  -- 00035 adds a unique index on analytics_sessions (studio_id, visitor_id, session_token).
  IF EXISTS (SELECT 1 FROM analytics_sessions GROUP BY studio_id, visitor_id, session_token HAVING count(*) > 1) THEN
    RAISE EXCEPTION 'duplicate analytics_sessions visits exist; clean them up before applying 00035';
  END IF;
END $$;

-- ===== 00035_attribution_phase1.sql =====
-- 00035: attribution and email automation, phase 1 (PRD-024 steps 1-3, PRD-027 phase 1)
--
-- Functions on the 00024 tables, plus the two automation tables.
-- (Built as 00025 on the PR branch; renumbered after main's 00025..00034 so
-- it applies last. Payments: main's 00031 stripe_events ledger and
-- fulfill_stripe_checkout() own idempotency; this file only adds the
-- conversion recording that runs after fulfilment.)
--   record_session()          anon-callable via the analytics-session Edge Function (service role)
--   link_visitor()            attach a browser/app visitor to a profile (one profile, many visitors)
--   record_conversion()       write a conversion with frozen first/converting touches; set
--                             studio_members.source/first touch the first time
--   get_attribution_sources() owner report: sessions, new people, conversions, revenue by
--                             channel/source/campaign under first- or last-touch
--   get_member_attribution()  "How they found you" for one member
--   get_automation_candidates() facts per person for the automation runner
-- All SECURITY DEFINER with fixed search_path. Writers are service-role only.

-- ===========================================================================
-- Sessions
-- ===========================================================================
CREATE UNIQUE INDEX IF NOT EXISTS uq_analytics_sessions_visit
  ON analytics_sessions (studio_id, visitor_id, session_token);

CREATE OR REPLACE FUNCTION record_session(
  p_studio_slug TEXT,
  p_visitor_id UUID,
  p_session_token TEXT,
  p_surface TEXT,
  p_landing_page_url TEXT,
  p_referrer_url TEXT,
  p_utm JSONB,
  p_click_ids JSONB,
  p_channel TEXT,
  p_device_type TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_studio UUID;
  v_id UUID;
  v_ref_host TEXT;
BEGIN
  SELECT id INTO v_studio FROM studios WHERE slug = p_studio_slug AND discoverable = TRUE;
  IF v_studio IS NULL THEN
    RETURN NULL;  -- unknown or private studio: record nothing, reveal nothing
  END IF;

  v_ref_host := NULLIF(substring(COALESCE(p_referrer_url, '') FROM '^[a-z]+://([^/:?#]+)'), '');

  INSERT INTO analytics_sessions (
    studio_id, session_token, visitor_id, surface,
    referrer_url, referrer_domain, landing_page_url,
    utm_source, utm_medium, utm_campaign, utm_content, utm_term,
    fbclid, fbc, fbp, gclid, gbraid, wbraid, ttclid, msclkid,
    channel, device_type, page_views
  ) VALUES (
    v_studio, left(p_session_token, 64), p_visitor_id, left(p_surface, 32),
    left(p_referrer_url, 1000), left(v_ref_host, 255), left(p_landing_page_url, 1000),
    left(p_utm->>'source', 200), left(p_utm->>'medium', 200), left(p_utm->>'campaign', 200),
    left(p_utm->>'content', 200), left(p_utm->>'term', 200),
    left(p_click_ids->>'fbclid', 500), left(p_click_ids->>'fbc', 500), left(p_click_ids->>'fbp', 500),
    left(p_click_ids->>'gclid', 500), left(p_click_ids->>'gbraid', 500), left(p_click_ids->>'wbraid', 500),
    left(p_click_ids->>'ttclid', 500), left(p_click_ids->>'msclkid', 500),
    left(p_channel, 32), left(p_device_type, 16), 1
  )
  -- One row per (studio, visitor, session token), atomically: a refresh or
  -- two overlapping page loads in the same session count page views on one
  -- row instead of creating a second visit.
  ON CONFLICT (studio_id, visitor_id, session_token)
    DO UPDATE SET page_views = analytics_sessions.page_views + 1
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;
REVOKE ALL ON FUNCTION record_session(TEXT, UUID, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_session(TEXT, UUID, TEXT, TEXT, TEXT, TEXT, JSONB, JSONB, TEXT, TEXT) TO service_role;

-- ===========================================================================
-- Identity
-- ===========================================================================
-- One owner per browser id (first link wins). Keep the earliest link if an
-- older install has duplicates.
DELETE FROM profile_visitors pv USING profile_visitors older
WHERE pv.visitor_id = older.visitor_id
  AND (pv.linked_at, pv.profile_id) > (older.linked_at, older.profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_profile_visitors_visitor ON profile_visitors (visitor_id);

CREATE OR REPLACE FUNCTION link_visitor(p_profile_id UUID, p_visitor_id UUID, p_via TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_profile_id IS NULL OR p_visitor_id IS NULL THEN RETURN; END IF;
  -- A browser id belongs to the first person who signed in on it. A shared
  -- household or front-desk browser must not merge two people's journeys;
  -- the client also starts a fresh visitor id when the account changes.
  -- Atomic: the unique index on visitor_id (below) makes the first link win
  -- even when two people link the same browser at the same moment.
  INSERT INTO profile_visitors (profile_id, visitor_id, linked_via)
  VALUES (p_profile_id, p_visitor_id, left(COALESCE(p_via, 'unknown'), 32))
  ON CONFLICT (visitor_id) DO NOTHING;
  IF NOT EXISTS (SELECT 1 FROM profile_visitors WHERE visitor_id = p_visitor_id AND profile_id = p_profile_id) THEN
    RETURN;  -- someone else owns this browser id
  END IF;
  UPDATE analytics_sessions SET profile_id = p_profile_id
  WHERE visitor_id = p_visitor_id AND profile_id IS NULL;
END;
$$;
REVOKE ALL ON FUNCTION link_visitor(UUID, UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION link_visitor(UUID, UUID, TEXT) TO service_role;

-- Signed-in clients link their own browser after sign-in / sign-up / claim.
-- auth.uid() decides whose profile; the caller only supplies the visitor id.
CREATE OR REPLACE FUNCTION link_my_visitor(p_visitor_id UUID, p_via TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN; END IF;
  PERFORM link_visitor(auth.uid(), p_visitor_id, p_via);
END;
$$;
REVOKE ALL ON FUNCTION link_my_visitor(UUID, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION link_my_visitor(UUID, TEXT) TO authenticated;

-- ===========================================================================
-- Conversions
-- ===========================================================================
CREATE OR REPLACE FUNCTION session_touch(p_session_id UUID)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'session_id', s.id, 'started_at', s.started_at, 'channel', s.channel, 'surface', s.surface,
    'utm_source', s.utm_source, 'utm_medium', s.utm_medium, 'utm_campaign', s.utm_campaign,
    'utm_content', s.utm_content, 'referrer_domain', s.referrer_domain,
    'landing_page_url', s.landing_page_url,
    'has_ad_click', (s.gclid IS NOT NULL OR s.gbraid IS NOT NULL OR s.wbraid IS NOT NULL
                     OR s.fbclid IS NOT NULL OR s.ttclid IS NOT NULL OR s.msclkid IS NOT NULL)
  )
  FROM analytics_sessions s WHERE s.id = p_session_id;
$$;
REVOKE ALL ON FUNCTION session_touch(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION session_touch(UUID) TO service_role;

-- The signature gained p_occurred_at; drop the ten-argument form so named
-- calls without it are not ambiguous between two overloads.
DROP FUNCTION IF EXISTS record_conversion(UUID, UUID, UUID, TEXT, INTEGER, TEXT, TEXT, UUID, UUID, TEXT);
CREATE OR REPLACE FUNCTION record_conversion(
  p_studio_id UUID,
  p_profile_id UUID,
  p_visitor_id UUID,
  p_conversion_type TEXT,
  p_value_cents INTEGER,
  p_currency TEXT,
  p_entity_type TEXT,
  p_entity_id UUID,
  p_converting_session_id UUID,
  p_member_source TEXT,
  -- When the booking or purchase actually happened. A retry passes the
  -- original time, so later visits don't join the journey and the conversion
  -- stays in the right reporting period. NULL means now.
  p_occurred_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_first UUID;
  v_last UUID;
  v_count INTEGER;
  v_first_at TIMESTAMPTZ;
  v_id UUID;
  v_at TIMESTAMPTZ := COALESCE(p_occurred_at, NOW());
BEGIN
  IF p_visitor_id IS NOT NULL AND p_profile_id IS NOT NULL THEN
    PERFORM link_visitor(p_profile_id, p_visitor_id, p_conversion_type);
  END IF;

  -- The journey: every session at this studio from any visitor linked to the
  -- person (or the anonymous visitor itself), up to the conversion.
  WITH visitors AS (
    SELECT visitor_id FROM profile_visitors WHERE profile_id = p_profile_id
    UNION
    SELECT p_visitor_id WHERE p_visitor_id IS NOT NULL
      AND NOT EXISTS (SELECT 1 FROM profile_visitors pv
                      WHERE pv.visitor_id = p_visitor_id AND pv.profile_id IS DISTINCT FROM p_profile_id)
  ), journey AS (
    SELECT s.id, s.started_at FROM analytics_sessions s
    WHERE s.visitor_id IN (SELECT visitor_id FROM visitors)
      AND (p_studio_id IS NULL OR s.studio_id = p_studio_id)
      AND s.started_at <= v_at
  )
  SELECT
    (SELECT id FROM journey ORDER BY started_at ASC, id LIMIT 1),
    (SELECT id FROM journey ORDER BY started_at DESC, id LIMIT 1),
    (SELECT count(*) FROM journey),
    (SELECT min(started_at) FROM journey)
  INTO v_first, v_last, v_count, v_first_at;

  -- An automatic renewal happens without a visit: it has no converting
  -- session, and borrowing the member's latest visit would credit an
  -- unrelated email or campaign with the charge.
  v_last := CASE WHEN p_conversion_type = 'membership_renewal' THEN p_converting_session_id
                 ELSE COALESCE(p_converting_session_id, v_last) END;

  INSERT INTO conversion_events (
    studio_id, profile_id, visitor_id, conversion_type, value_cents, currency,
    entity_type, entity_id, first_touch_session_id, converting_touch_session_id,
    first_touch, converting_touch, touch_count, days_to_convert, occurred_at
  ) VALUES (
    p_studio_id, p_profile_id, p_visitor_id, p_conversion_type, p_value_cents, upper(p_currency),
    p_entity_type, p_entity_id, v_first, v_last,
    session_touch(v_first), session_touch(v_last), COALESCE(v_count, 0),
    CASE WHEN v_first_at IS NULL THEN NULL ELSE GREATEST(0, (v_at::date - v_first_at::date)) END,
    v_at
  )
  ON CONFLICT (conversion_type, entity_type, entity_id) WHERE entity_id IS NOT NULL DO NOTHING
  RETURNING id INTO v_id;

  -- First time this person has a relationship with this studio: record where
  -- it came from. Never overwritten.
  -- A signed-in member's first booking or purchase may be their first contact
  -- with the studio (only express booking and import create the row
  -- otherwise), so create the relationship here if it is missing.
  IF p_studio_id IS NOT NULL AND p_profile_id IS NOT NULL THEN
    INSERT INTO studio_members (studio_id, profile_id, source, first_touch_session_id, acquired_at)
    VALUES (p_studio_id, p_profile_id, p_member_source, v_first, v_at)
    ON CONFLICT (studio_id, profile_id) DO UPDATE SET
      source = COALESCE(studio_members.source, EXCLUDED.source),
      first_touch_session_id = COALESCE(studio_members.first_touch_session_id, EXCLUDED.first_touch_session_id),
      acquired_at = COALESCE(studio_members.acquired_at, EXCLUDED.acquired_at);
  END IF;

  RETURN v_id;
END;
$$;
REVOKE ALL ON FUNCTION record_conversion(UUID, UUID, UUID, TEXT, INTEGER, TEXT, TEXT, UUID, UUID, TEXT, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_conversion(UUID, UUID, UUID, TEXT, INTEGER, TEXT, TEXT, UUID, UUID, TEXT, TIMESTAMPTZ) TO service_role;

-- ===========================================================================
-- Consent (append-only)
-- ===========================================================================
-- NOW() is fixed for a whole transaction, so an opt-in and an opt-out written
-- in one request would tie and "latest wins" would be a coin toss. A per-row
-- clock plus a sequence makes the order total.
ALTER TABLE consent_records ALTER COLUMN captured_at SET DEFAULT clock_timestamp();
ALTER TABLE consent_records ADD COLUMN IF NOT EXISTS seq BIGSERIAL;
CREATE OR REPLACE FUNCTION record_consent(
  p_studio_id UUID, p_profile_id UUID, p_visitor_id UUID,
  p_purpose TEXT, p_granted BOOLEAN, p_source TEXT, p_policy_version TEXT
)
RETURNS VOID
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  INSERT INTO consent_records (studio_id, profile_id, visitor_id, purpose, granted, source, policy_version)
  VALUES (p_studio_id, p_profile_id, p_visitor_id, p_purpose, p_granted, left(p_source, 64), p_policy_version);
$$;
REVOKE ALL ON FUNCTION record_consent(UUID, UUID, UUID, TEXT, BOOLEAN, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_consent(UUID, UUID, UUID, TEXT, BOOLEAN, TEXT, TEXT) TO service_role;

CREATE OR REPLACE FUNCTION has_consent(p_studio_id UUID, p_profile_id UUID, p_purpose TEXT)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((
    SELECT granted FROM consent_records
    WHERE profile_id = p_profile_id AND studio_id = p_studio_id AND purpose = p_purpose
    ORDER BY captured_at DESC, seq DESC LIMIT 1
  ), FALSE);
$$;
REVOKE ALL ON FUNCTION has_consent(UUID, UUID, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION has_consent(UUID, UUID, TEXT) TO service_role;


-- How much of a conversion's money was refunded. Conversion values are frozen
-- at purchase; refunds land on the transaction (record_stripe_refund, 00031).
-- One helper so the Sources report and the member page always agree.
CREATE OR REPLACE FUNCTION conversion_refunded_cents(p_studio_id UUID, p_entity_type TEXT, p_entity_id UUID)
RETURNS INTEGER
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE((
    SELECT COALESCE(tx.refunded_amount_cents, 0)
    FROM transactions tx
    WHERE tx.studio_id = p_studio_id
      AND ((p_entity_type = 'transaction' AND tx.id = p_entity_id)
        OR (p_entity_type = 'class_pack' AND tx.class_pack_id = p_entity_id)
        OR (p_entity_type = 'membership' AND tx.membership_id = p_entity_id))
    ORDER BY tx.created_at ASC
    LIMIT 1
  ), 0);
$$;
REVOKE ALL ON FUNCTION conversion_refunded_cents(UUID, TEXT, UUID) FROM PUBLIC, anon, authenticated;

-- ===========================================================================
-- Owner reports
-- ===========================================================================
-- Takes the studio the manage UI is showing (p_studio_id). Without it the
-- function would pick a studio on its own, which for multi-studio staff can
-- differ from the one on screen. Drop the old three-argument form.
DROP FUNCTION IF EXISTS get_attribution_sources(TIMESTAMPTZ, TIMESTAMPTZ, TEXT);
CREATE OR REPLACE FUNCTION get_attribution_sources(
  p_from TIMESTAMPTZ, p_to TIMESTAMPTZ, p_model TEXT DEFAULT 'first', p_studio_id UUID DEFAULT NULL
)
RETURNS TABLE (
  channel TEXT, utm_source TEXT, utm_campaign TEXT,
  sessions BIGINT, new_people BIGINT, bookings BIGINT, purchases BIGINT, revenue_cents BIGINT
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH my AS (
    -- Only a studio the caller is an active owner/admin of; nothing otherwise.
    SELECT ss.studio_id FROM studio_staff ss
    WHERE ss.profile_id = auth.uid() AND ss.is_active = TRUE
      AND ss.role IN ('owner', 'admin')
      AND (p_studio_id IS NULL OR ss.studio_id = p_studio_id)
    ORDER BY ss.created_at ASC LIMIT 1
  ),
  sess AS (
    SELECT COALESCE(s.channel, 'direct') AS channel, COALESCE(s.utm_source, s.referrer_domain, '') AS utm_source,
           COALESCE(s.utm_campaign, '') AS utm_campaign, count(*) AS sessions
    FROM analytics_sessions s, my
    WHERE s.studio_id = my.studio_id AND s.started_at >= p_from AND s.started_at < p_to
    GROUP BY 1, 2, 3
  ),
  conv AS (
    SELECT
      COALESCE(t->>'channel', CASE WHEN c.conversion_type = 'membership_renewal' THEN 'renewal' ELSE 'unknown' END) AS channel,
      COALESCE(t->>'utm_source', t->>'referrer_domain', '') AS utm_source,
      COALESCE(t->>'utm_campaign', '') AS utm_campaign,
      count(*) FILTER (WHERE c.conversion_type IN ('guest_booking', 'member_booking')) AS bookings,
      -- Money in after refunds: the conversion value is frozen at purchase,
      -- refunds live on the transaction (record_stripe_refund), so net them
      -- here. A fully refunded purchase is no longer a purchase.
      count(*) FILTER (WHERE x.net > 0) AS purchases,
      COALESCE(sum(x.net), 0) AS revenue_cents
    FROM conversion_events c
    CROSS JOIN my
    CROSS JOIN LATERAL (
      SELECT CASE WHEN p_model = 'last' THEN c.converting_touch ELSE c.first_touch END AS t,
             GREATEST(0, COALESCE(c.value_cents, 0)
               - conversion_refunded_cents(c.studio_id, c.entity_type, c.entity_id)) AS net
    ) x
    WHERE c.studio_id = my.studio_id AND c.occurred_at >= p_from AND c.occurred_at < p_to
    GROUP BY 1, 2, 3
  ),
  people AS (
    SELECT COALESCE(s.channel, 'unknown') AS channel, COALESCE(s.utm_source, s.referrer_domain, '') AS utm_source,
           COALESCE(s.utm_campaign, '') AS utm_campaign, count(*) AS new_people
    FROM studio_members m
    JOIN my ON my.studio_id = m.studio_id
    LEFT JOIN analytics_sessions s ON s.id = m.first_touch_session_id
    WHERE m.acquired_at >= p_from AND m.acquired_at < p_to
      -- Moved over from another system, or already a member before tracking
      -- began: not newly acquired.
      AND COALESCE(m.source, '') NOT IN ('import', 'pre_tracking')
    GROUP BY 1, 2, 3
  )
  SELECT k.channel, NULLIF(k.utm_source, ''), NULLIF(k.utm_campaign, ''),
         COALESCE(sess.sessions, 0), COALESCE(people.new_people, 0),
         COALESCE(conv.bookings, 0), COALESCE(conv.purchases, 0), COALESCE(conv.revenue_cents, 0)
  FROM (
    SELECT channel, utm_source, utm_campaign FROM sess
    UNION SELECT channel, utm_source, utm_campaign FROM conv
    UNION SELECT channel, utm_source, utm_campaign FROM people
  ) k
  LEFT JOIN sess USING (channel, utm_source, utm_campaign)
  LEFT JOIN conv USING (channel, utm_source, utm_campaign)
  LEFT JOIN people USING (channel, utm_source, utm_campaign)
  ORDER BY COALESCE(conv.revenue_cents, 0) DESC, COALESCE(sess.sessions, 0) DESC;
$$;
REVOKE ALL ON FUNCTION get_attribution_sources(TIMESTAMPTZ, TIMESTAMPTZ, TEXT, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_attribution_sources(TIMESTAMPTZ, TIMESTAMPTZ, TEXT, UUID) TO authenticated;

DROP FUNCTION IF EXISTS get_member_attribution(UUID);
CREATE OR REPLACE FUNCTION get_member_attribution(p_profile_id UUID, p_studio_id UUID DEFAULT NULL)
RETURNS TABLE (
  source TEXT, acquired_at TIMESTAMPTZ, first_touch JSONB,
  conversions JSONB
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH my AS (
    SELECT ss.studio_id FROM studio_staff ss
    WHERE ss.profile_id = auth.uid() AND ss.is_active = TRUE
      AND (p_studio_id IS NULL OR ss.studio_id = p_studio_id)
    ORDER BY ss.created_at ASC LIMIT 1
  )
  SELECT m.source, m.acquired_at, session_touch(m.first_touch_session_id),
         COALESCE((
           SELECT jsonb_agg(jsonb_build_object(
             -- Net of refunds, like the Sources report; the original amount stays available.
             'type', c.conversion_type,
             'value_cents', GREATEST(0, COALESCE(c.value_cents, 0) - conversion_refunded_cents(c.studio_id, c.entity_type, c.entity_id)),
             'gross_value_cents', c.value_cents, 'currency', c.currency,
             'occurred_at', c.occurred_at, 'first_touch', c.first_touch,
             'converting_touch', c.converting_touch, 'days_to_convert', c.days_to_convert
           ) ORDER BY c.occurred_at)
           FROM conversion_events c WHERE c.studio_id = m.studio_id AND c.profile_id = m.profile_id
         ), '[]'::jsonb)
  FROM studio_members m JOIN my ON my.studio_id = m.studio_id
  WHERE m.profile_id = p_profile_id;
$$;
REVOKE ALL ON FUNCTION get_member_attribution(UUID, UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_member_attribution(UUID, UUID) TO authenticated;

-- ===========================================================================
-- Staff authorization without RLS recursion (PR #72 review)
-- ===========================================================================
-- 00001's "Staff can view co-workers" policy on studio_staff queries
-- studio_staff, so any policy that looks at studio_staff from a client
-- session fails with "infinite recursion detected" (00017 and 00020 worked
-- around it per call). These helpers read studio_staff as the function owner,
-- outside RLS, and the co-workers policy is rebuilt on top of them, which
-- fixes every staff policy that reads studio_staff, old and new.
-- my_staff_studio_ids() and the rebuilt "Staff can view co-workers" policy
-- come from main's 00026 (same definition: active assignments only).

CREATE OR REPLACE FUNCTION is_studio_staff(p_studio_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM studio_staff
                 WHERE studio_id = p_studio_id AND profile_id = auth.uid() AND is_active = TRUE);
$$;
REVOKE ALL ON FUNCTION is_studio_staff(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_studio_staff(UUID) TO authenticated;

CREATE OR REPLACE FUNCTION is_studio_admin(p_studio_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM studio_staff
                 WHERE studio_id = p_studio_id AND profile_id = auth.uid() AND is_active = TRUE
                   AND role IN ('owner', 'admin'));
$$;
REVOKE ALL ON FUNCTION is_studio_admin(UUID) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION is_studio_admin(UUID) TO authenticated;

-- The 00024 staff-read policies, rebuilt on the helpers.
DROP POLICY IF EXISTS conversion_events_staff_read ON conversion_events;
CREATE POLICY conversion_events_staff_read ON conversion_events
  FOR SELECT TO authenticated USING (is_studio_staff(studio_id));
DROP POLICY IF EXISTS consent_records_staff_read ON consent_records;
CREATE POLICY consent_records_staff_read ON consent_records
  FOR SELECT TO authenticated USING (studio_id IS NOT NULL AND is_studio_staff(studio_id));
DROP POLICY IF EXISTS ad_integrations_admin_read ON ad_integrations;
CREATE POLICY ad_integrations_admin_read ON ad_integrations
  FOR SELECT TO authenticated USING (is_studio_admin(studio_id));
DROP POLICY IF EXISTS conversion_deliveries_admin_read ON conversion_deliveries;
CREATE POLICY conversion_deliveries_admin_read ON conversion_deliveries
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM ad_integrations ai
                 WHERE ai.id = conversion_deliveries.ad_integration_id AND is_studio_admin(ai.studio_id)));

-- ===========================================================================
-- Email automations (phase 1: three sequences)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS automation_settings (
  studio_id UUID PRIMARY KEY REFERENCES studios(id) ON DELETE CASCADE,
  guest_to_member_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  first_visit_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  lapsed_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  lapsed_days_override INTEGER CHECK (lapsed_days_override IS NULL OR lapsed_days_override BETWEEN 7 AND 120),
  intro_offer_url TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
COMMENT ON TABLE automation_settings IS
  'Per-studio switches for the phase-1 automations. A studio with no row gets the defaults (all on). Owners/admins edit via /manage.';

CREATE TABLE IF NOT EXISTS automation_sends (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  studio_id UUID NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  profile_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  automation_key TEXT NOT NULL CHECK (automation_key IN ('guest_to_member', 'first_visit', 'lapsed')),
  step INTEGER NOT NULL,
  episode_key TEXT NOT NULL,            -- e.g. the lapse's last-visit date, so a person lapses once per episode
  -- sending: claimed, not yet confirmed by the provider. Only 'sent' counts
  -- as delivered history; a stuck 'sending' row blocks a resend (no duplicate)
  -- and never advances a sequence.
  status TEXT NOT NULL DEFAULT 'sending' CHECK (status IN ('sending', 'sent', 'failed')),
  error TEXT,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (studio_id, profile_id, automation_key, step, episode_key)
);
CREATE INDEX IF NOT EXISTS idx_automation_sends_recent ON automation_sends(profile_id, sent_at DESC);

ALTER TABLE automation_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE automation_sends ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS automation_settings_admin ON automation_settings;
CREATE POLICY automation_settings_admin ON automation_settings
  FOR ALL TO authenticated
  USING (is_studio_admin(studio_id))
  WITH CHECK (is_studio_admin(studio_id));

DROP POLICY IF EXISTS automation_sends_staff_read ON automation_sends;
CREATE POLICY automation_sends_staff_read ON automation_sends
  FOR SELECT TO authenticated
  USING (is_studio_staff(studio_id));

-- Facts per person for the runner (src/lib/marketing/automations.ts decides).
CREATE OR REPLACE FUNCTION get_automation_candidates(p_studio_id UUID)
RETURNS TABLE (
  profile_id UUID, email TEXT, first_name TEXT,
  is_guest BOOLEAN, claimed_at TIMESTAMPTZ,
  email_consent BOOLEAN,
  first_booking_at TIMESTAMPTZ, guest_booking_at TIMESTAMPTZ,
  first_check_in_at TIMESTAMPTZ, last_visit_at TIMESTAMPTZ,
  visit_count BIGINT, booking_count BIGINT, median_gap_days NUMERIC,
  has_active_membership BOOLEAN, has_active_pack BOOLEAN,
  has_upcoming_booking BOOLEAN,
  sends JSONB
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH members AS (
    SELECT m.profile_id FROM studio_members m WHERE m.studio_id = p_studio_id
  ),
  b AS (
    SELECT bk.profile_id, bk.created_at, bk.checked_in_at, bk.status
    FROM bookings bk JOIN members USING (profile_id)
    WHERE bk.studio_id = p_studio_id AND bk.status NOT IN ('cancelled', 'late_cancel')
  ),
  visits AS (
    SELECT profile_id, checked_in_at,
           checked_in_at - lag(checked_in_at) OVER (PARTITION BY profile_id ORDER BY checked_in_at) AS gap
    FROM b WHERE checked_in_at IS NOT NULL
  )
  SELECT
    p.id, p.email, p.first_name,
    COALESCE(p.is_guest, FALSE), p.claimed_at,
    has_consent(p_studio_id, p.id, 'email_marketing'),
    (SELECT min(created_at) FROM b WHERE b.profile_id = p.id),
    -- Latest guest booking: the follow-up is about the visit that just happened.
    -- Confirmed (or attended) seats only: a guest still on the waitlist was never booked.
    CASE WHEN COALESCE(p.is_guest, FALSE) THEN (SELECT max(created_at) FROM b WHERE b.profile_id = p.id
      AND b.status IN ('confirmed', 'checked_in', 'no_show')) END,
    (SELECT min(checked_in_at) FROM visits v WHERE v.profile_id = p.id),
    (SELECT max(checked_in_at) FROM visits v WHERE v.profile_id = p.id),
    (SELECT count(*) FROM visits v WHERE v.profile_id = p.id),
    (SELECT count(*) FROM b WHERE b.profile_id = p.id),
    (SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM gap) / 86400.0)
       FROM visits v WHERE v.profile_id = p.id AND gap IS NOT NULL)::numeric,
    EXISTS (SELECT 1 FROM memberships ms WHERE ms.profile_id = p.id AND ms.studio_id = p_studio_id
            AND ms.status IN ('active', 'paused', 'past_due')),
    EXISTS (SELECT 1 FROM class_packs cp WHERE cp.profile_id = p.id AND cp.studio_id = p_studio_id
            AND cp.status = 'active' AND COALESCE(cp.classes_remaining, 0) > 0
            AND (cp.expires_at IS NULL OR cp.expires_at > NOW())),
    -- Already coming back: a lapsed check-in would be wrong.
    EXISTS (SELECT 1 FROM bookings ub JOIN class_occurrences o ON o.id = ub.class_occurrence_id
            WHERE ub.profile_id = p.id AND ub.studio_id = p_studio_id
              AND ub.status IN ('confirmed', 'waitlisted') AND o.starts_at > NOW()),
    COALESCE((SELECT jsonb_agg(jsonb_build_object('key', s.automation_key, 'step', s.step,
                'episode', s.episode_key, 'sent_at', s.sent_at, 'pending', s.status = 'sending'))
              -- Failed sends are dropped. Unresolved 'sending' claims come back
              -- flagged pending: they count for the daily cap and the
              -- intro-offer rule (the provider may have delivered them) but
              -- never advance a sequence.
              FROM automation_sends s WHERE s.profile_id = p.id AND s.studio_id = p_studio_id
                AND s.status IN ('sent', 'sending')), '[]'::jsonb)
  FROM profiles p JOIN members ON members.profile_id = p.id
  WHERE p.email IS NOT NULL;
$$;
REVOKE ALL ON FUNCTION get_automation_candidates(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION get_automation_candidates(UUID) TO service_role;

-- ===========================================================================
-- Member bookings made by the member themselves (PR #72 review)
-- ===========================================================================
-- book_class() and book_free_class() run as the signed-in member. Count those
-- bookings as conversions without touching the booking functions: an AFTER
-- INSERT trigger fires only when the inserting session IS the member
-- (auth.uid() = profile_id). Service-role paths (express-book, the Stripe
-- webhook's drop-in booking) have no auth.uid() and record their own
-- conversion with the converting session and the payment. Analytics never
-- blocks a booking: any error here is swallowed.
-- Conversions a booking trigger couldn't write (a transient error must not
-- fail the booking). run-automations drains this hourly via
-- retry_queued_conversions(); record_conversion is idempotent per entity.
CREATE TABLE IF NOT EXISTS conversion_retry_queue (
  id BIGSERIAL PRIMARY KEY,
  args JSONB NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE conversion_retry_queue ENABLE ROW LEVEL SECURITY;
-- Service role only; an explicit deny-all keeps SEC-07 meaningful.
DROP POLICY IF EXISTS "No client access to conversion retry queue" ON conversion_retry_queue;
CREATE POLICY "No client access to conversion retry queue" ON conversion_retry_queue
  FOR ALL USING (FALSE) WITH CHECK (FALSE);

-- The booking page's analytics session, sent as the x-tandava-session request
-- header on the booking RPC. Trusted only if it is this person's own visit at
-- this studio.
CREATE OR REPLACE FUNCTION booking_session_from_request(p_profile_id UUID, p_studio_id UUID)
RETURNS UUID
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_raw TEXT;
  v_id UUID;
BEGIN
  BEGIN
    v_raw := current_setting('request.headers', true)::json->>'x-tandava-session';
  EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
  END;
  IF v_raw IS NULL OR v_raw !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN
    RETURN NULL;
  END IF;
  SELECT s.id INTO v_id FROM analytics_sessions s
  WHERE s.id = v_raw::uuid AND s.studio_id = p_studio_id
    AND (s.profile_id = p_profile_id
         OR s.visitor_id IN (SELECT visitor_id FROM profile_visitors WHERE profile_id = p_profile_id));
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION record_booking_conversion_or_queue(
  p_studio_id UUID, p_profile_id UUID, p_type TEXT, p_booking_id UUID, p_session UUID, p_source TEXT
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_args JSONB := jsonb_build_object(
    'p_studio_id', p_studio_id, 'p_profile_id', p_profile_id, 'p_visitor_id', NULL,
    'p_conversion_type', p_type, 'p_value_cents', 0,
    'p_currency', (SELECT currency FROM studios WHERE id = p_studio_id),
    'p_entity_type', 'booking', 'p_entity_id', p_booking_id,
    'p_converting_session_id', p_session, 'p_member_source', p_source,
    -- The booking's own time, kept for a retry.
    'p_occurred_at', NOW());
BEGIN
  BEGIN
    PERFORM record_conversion(p_studio_id, p_profile_id, NULL, p_type, 0,
      v_args->>'p_currency', 'booking', p_booking_id, p_session, p_source, NOW());
  EXCEPTION WHEN OTHERS THEN
    BEGIN
      INSERT INTO conversion_retry_queue (args, last_error) VALUES (v_args, left(SQLERRM, 500));
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING 'booking conversion lost: %', SQLERRM;
    END;
  END;
END;
$$;
REVOKE ALL ON FUNCTION record_booking_conversion_or_queue(UUID, UUID, TEXT, UUID, UUID, TEXT) FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION retry_queued_conversions(p_limit INTEGER DEFAULT 500)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r RECORD;
  v_done INTEGER := 0;
BEGIN
  FOR r IN SELECT * FROM conversion_retry_queue WHERE attempts < 10 ORDER BY id LIMIT p_limit FOR UPDATE SKIP LOCKED LOOP
    BEGIN
      PERFORM record_conversion(
        (r.args->>'p_studio_id')::uuid, (r.args->>'p_profile_id')::uuid, (r.args->>'p_visitor_id')::uuid,
        r.args->>'p_conversion_type', (r.args->>'p_value_cents')::int, r.args->>'p_currency',
        r.args->>'p_entity_type', (r.args->>'p_entity_id')::uuid,
        (r.args->>'p_converting_session_id')::uuid, r.args->>'p_member_source',
        (r.args->>'p_occurred_at')::timestamptz);
      DELETE FROM conversion_retry_queue WHERE id = r.id;
      v_done := v_done + 1;
    EXCEPTION WHEN OTHERS THEN
      UPDATE conversion_retry_queue SET attempts = attempts + 1, last_error = left(SQLERRM, 500) WHERE id = r.id;
    END;
  END LOOP;
  RETURN v_done;
END;
$$;
REVOKE ALL ON FUNCTION retry_queued_conversions(INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION retry_queued_conversions(INTEGER) TO service_role;

-- How a waitlisted booking was made, captured when it is made, so the
-- conversion recorded at promotion (maybe days later) keeps its origin and
-- visit even if the guest has since saved an account or visited again.
CREATE TABLE IF NOT EXISTS booking_attribution_context (
  booking_id UUID PRIMARY KEY REFERENCES bookings(id) ON DELETE CASCADE,
  studio_id UUID NOT NULL REFERENCES studios(id) ON DELETE CASCADE,
  origin TEXT NOT NULL CHECK (origin IN ('express', 'member')),
  session_id UUID REFERENCES analytics_sessions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE booking_attribution_context ENABLE ROW LEVEL SECURITY;
-- Written by triggers and express-book (service role) only.
DROP POLICY IF EXISTS "No client access to booking attribution context" ON booking_attribution_context;
CREATE POLICY "No client access to booking attribution context" ON booking_attribution_context
  FOR ALL USING (FALSE) WITH CHECK (FALSE);

CREATE OR REPLACE FUNCTION record_member_booking_conversion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- A guest's waitlist spot made by the service role (express booking): record
  -- its origin in the same transaction as the booking, so it can't be lost.
  -- express-book then adds the validated visit.
  IF NEW.status = 'waitlisted' AND auth.uid() IS NULL
     AND EXISTS (SELECT 1 FROM profiles WHERE id = NEW.profile_id AND is_guest IS TRUE) THEN
    INSERT INTO booking_attribution_context (booking_id, studio_id, origin)
    VALUES (NEW.id, NEW.studio_id, 'express')
    ON CONFLICT (booking_id) DO NOTHING;
  END IF;
  IF auth.uid() IS NOT NULL AND auth.uid() = NEW.profile_id THEN
    IF NEW.status = 'confirmed' THEN
      PERFORM record_booking_conversion_or_queue(
        NEW.studio_id, NEW.profile_id, 'member_booking', NEW.id,
        booking_session_from_request(NEW.profile_id, NEW.studio_id), 'signup');
    ELSIF NEW.status = 'waitlisted' THEN
      INSERT INTO booking_attribution_context (booking_id, studio_id, origin, session_id)
      VALUES (NEW.id, NEW.studio_id, 'member', booking_session_from_request(NEW.profile_id, NEW.studio_id))
      ON CONFLICT (booking_id) DO NOTHING;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_member_booking_conversion ON bookings;
CREATE TRIGGER trg_member_booking_conversion
  AFTER INSERT ON bookings
  FOR EACH ROW EXECUTE FUNCTION record_member_booking_conversion();

-- A waitlisted booking that gets promoted becomes a booking then, whoever
-- triggers the promotion (a cancellation, staff, a job). Paths that record
-- their own conversion never record a waitlisted booking, and the per-entity
-- unique index stops any duplicate.
CREATE OR REPLACE FUNCTION record_promoted_booking_conversion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_guest BOOLEAN;
  v_ctx booking_attribution_context%ROWTYPE;
  v_session UUID;
BEGIN
  IF OLD.status = 'waitlisted' AND NEW.status = 'confirmed' THEN
    SELECT * INTO v_ctx FROM booking_attribution_context WHERE booking_id = NEW.id;
    IF FOUND THEN
      -- Origin and visit as they were when the person joined the waitlist.
      v_guest := v_ctx.origin = 'express';
      v_session := COALESCE(v_ctx.session_id, (
        SELECT s.id FROM analytics_sessions s
        WHERE s.studio_id = NEW.studio_id AND s.started_at <= v_ctx.created_at
          AND (s.profile_id = NEW.profile_id
               OR s.visitor_id IN (SELECT visitor_id FROM profile_visitors WHERE profile_id = NEW.profile_id))
        ORDER BY s.started_at DESC LIMIT 1));
    ELSE
      -- Waitlisted before this context existed: best available guess.
      SELECT COALESCE(is_guest, FALSE) INTO v_guest FROM profiles WHERE id = NEW.profile_id;
      v_session := NULL;
    END IF;
    PERFORM record_booking_conversion_or_queue(
      NEW.studio_id, NEW.profile_id,
      CASE WHEN v_guest THEN 'guest_booking' ELSE 'member_booking' END,
      NEW.id, v_session, CASE WHEN v_guest THEN 'express' ELSE 'signup' END);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_promoted_booking_conversion ON bookings;
CREATE TRIGGER trg_promoted_booking_conversion
  AFTER UPDATE OF status ON bookings
  FOR EACH ROW EXECUTE FUNCTION record_promoted_booking_conversion();

-- ===========================================================================
-- Signup consent, scoped to the studio the person signed up from (PR #72 review)
-- ===========================================================================
-- Register stores marketing_consent and, when the sign-up started on a studio
-- page, marketing_consent_studio (the slug) in the auth metadata. Applied on
-- sign-in (email confirmation means there is no session at sign-up), once:
-- a later change of mind is recorded by the unsubscribe link or a settings
-- toggle and is never overwritten by this. A sign-up from no studio page
-- records nothing: consent is to a sender, not to Tandava in general.
CREATE OR REPLACE FUNCTION apply_my_signup_consent(
  p_studio_slug TEXT DEFAULT NULL, p_granted BOOLEAN DEFAULT NULL, p_started_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_meta JSONB;
  v_created TIMESTAMPTZ;
  v_slug TEXT;
  v_granted BOOLEAN;
  v_studio UUID;
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  SELECT raw_user_meta_data, created_at INTO v_meta, v_created FROM auth.users WHERE id = auth.uid();
  -- Email sign-ups carry the choice in metadata; OAuth sign-ups (no metadata)
  -- pass the choice the browser kept across the redirect. Either way it is
  -- the person's own choice about their own email.
  IF COALESCE(v_meta->>'marketing_consent_studio', '') <> '' THEN
    v_slug := v_meta->>'marketing_consent_studio';
    v_granted := COALESCE((v_meta->>'marketing_consent')::boolean, FALSE);
  ELSIF p_studio_slug IS NOT NULL AND p_granted IS NOT NULL AND p_started_at IS NOT NULL
        -- Only the account this browser just created: one made within an hour
        -- after the Google sign-up started. A cancelled attempt followed by
        -- someone else signing in to an existing account applies nothing.
        AND v_created BETWEEN p_started_at - interval '5 minutes' AND p_started_at + interval '1 hour' THEN
    v_slug := p_studio_slug;
    v_granted := p_granted;
  ELSE
    RETURN FALSE;
  END IF;
  SELECT id INTO v_studio FROM studios WHERE slug = v_slug;
  IF v_studio IS NULL THEN RETURN FALSE; END IF;
  IF EXISTS (
    SELECT 1 FROM consent_records
    WHERE studio_id = v_studio AND profile_id = auth.uid() AND purpose = 'email_marketing'
  ) THEN
    RETURN FALSE;
  END IF;
  INSERT INTO consent_records (studio_id, profile_id, purpose, granted, source, policy_version)
  VALUES (v_studio, auth.uid(), 'email_marketing', v_granted, 'signup_form', '2026-10');
  RETURN TRUE;
END;
$$;
REVOKE ALL ON FUNCTION apply_my_signup_consent(TEXT, BOOLEAN, TIMESTAMPTZ) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION apply_my_signup_consent(TEXT, BOOLEAN, TIMESTAMPTZ) TO authenticated;

-- ===========================================================================
-- Paid conversions, recorded after main's SQL fulfilment (00031)
-- ===========================================================================
-- The Stripe webhook first calls fulfill_stripe_checkout() (idempotent by
-- Stripe event id, one transaction), then record_checkout_conversion() with
-- the same session and the event's own time. This reads what fulfilment
-- wrote (the transaction for this Checkout Session and what it bought) and
-- records the conversion with frozen first/converting touches. It is
-- idempotent per (type, entity), so it is safe on a duplicate delivery, and
-- it never raises: a failure goes to conversion_retry_queue (drained hourly by
-- run-automations), so analytics never makes Stripe retry a payment.
CREATE OR REPLACE FUNCTION record_conversion_or_queue(p_args JSONB)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_id UUID;
BEGIN
  BEGIN
    v_id := record_conversion(
      (p_args->>'p_studio_id')::uuid, (p_args->>'p_profile_id')::uuid, (p_args->>'p_visitor_id')::uuid,
      p_args->>'p_conversion_type', (p_args->>'p_value_cents')::int, p_args->>'p_currency',
      p_args->>'p_entity_type', (p_args->>'p_entity_id')::uuid,
      (p_args->>'p_converting_session_id')::uuid, p_args->>'p_member_source',
      (p_args->>'p_occurred_at')::timestamptz);
    RETURN v_id;
  EXCEPTION WHEN OTHERS THEN
    BEGIN
      INSERT INTO conversion_retry_queue (args, last_error) VALUES (p_args, left(SQLERRM, 500));
    EXCEPTION WHEN OTHERS THEN
      RAISE WARNING 'conversion lost: %', SQLERRM;
    END;
    RETURN NULL;
  END;
END;
$$;
REVOKE ALL ON FUNCTION record_conversion_or_queue(JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_conversion_or_queue(JSONB) TO service_role;

CREATE OR REPLACE FUNCTION record_checkout_conversion(p_session JSONB, p_occurred_at TIMESTAMPTZ DEFAULT NULL)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  c_uuid CONSTANT TEXT := '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';
  v_meta    JSONB := COALESCE(p_session -> 'metadata', '{}'::jsonb);
  v_sid     TEXT  := NULLIF(p_session ->> 'id', '');
  v_pi      TEXT  := NULLIF(p_session ->> 'payment_intent', '');
  v_express BOOLEAN := (v_meta ->> 'express') = '1';
  v_txn     transactions%ROWTYPE;
  v_type    TEXT;
  v_etype   TEXT;
  v_eid     UUID;
BEGIN
  -- What fulfilment wrote for this payment; nothing means it was ignored or
  -- has not committed, and there is nothing to credit.
  SELECT * INTO v_txn FROM transactions
  WHERE (v_sid IS NOT NULL AND stripe_checkout_session_id = v_sid)
     OR (v_pi IS NOT NULL AND stripe_payment_intent_id = v_pi)
  ORDER BY created_at LIMIT 1;
  IF NOT FOUND OR v_txn.profile_id IS NULL THEN RETURN NULL; END IF;

  CASE v_meta ->> 'type'
    WHEN 'drop_in' THEN
      -- Only a confirmed seat is a booking. A payment flagged for refund (class
      -- full, cancelled, duplicate) is still money in, under its own type.
      v_type := CASE WHEN EXISTS (SELECT 1 FROM bookings WHERE transaction_id = v_txn.id AND status = 'confirmed')
                     THEN CASE WHEN v_express THEN 'guest_booking' ELSE 'member_booking' END
                     ELSE 'drop_in_payment' END;
      v_etype := 'transaction'; v_eid := v_txn.id;
    WHEN 'membership' THEN
      v_type := 'membership_start'; v_etype := 'membership'; v_eid := v_txn.membership_id;
    WHEN 'class_pack' THEN
      v_type := 'pack_purchase'; v_etype := 'class_pack'; v_eid := v_txn.class_pack_id;
    WHEN 'workshop' THEN
      v_type := 'event_registration'; v_etype := 'transaction'; v_eid := v_txn.id;
    ELSE
      RETURN NULL;
  END CASE;
  IF v_eid IS NULL THEN RETURN NULL; END IF;

  RETURN record_conversion_or_queue(jsonb_build_object(
    'p_studio_id', v_txn.studio_id, 'p_profile_id', v_txn.profile_id,
    'p_visitor_id', CASE WHEN (v_meta ->> 'visitor_id') ~* c_uuid THEN v_meta ->> 'visitor_id' END,
    'p_conversion_type', v_type, 'p_value_cents', COALESCE(v_txn.amount_cents, 0),
    'p_currency', upper(COALESCE(v_txn.currency, p_session ->> 'currency', 'USD')),
    'p_entity_type', v_etype, 'p_entity_id', v_eid,
    -- Checked by stripe-checkout (this person's own visit at this studio).
    'p_converting_session_id', CASE WHEN (v_meta ->> 'session_id') ~* c_uuid THEN v_meta ->> 'session_id' END,
    'p_member_source', CASE WHEN v_express THEN 'express' ELSE 'signup' END,
    -- Stripe's event time: a late or retried delivery keeps the purchase's own moment.
    'p_occurred_at', COALESCE(p_occurred_at, NOW())));
END;
$$;
REVOKE ALL ON FUNCTION record_checkout_conversion(JSONB, TIMESTAMPTZ) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_checkout_conversion(JSONB, TIMESTAMPTZ) TO service_role;

-- A paid subscription renewal (invoice.paid, billing_reason subscription_cycle),
-- after renew_membership_cycle(). Keyed by the Stripe invoice id, so a retry
-- records nothing new. No converting visit: a renewal happens without one.
-- Signature gained p_payment_intent; drop the five-argument form.
DROP FUNCTION IF EXISTS record_renewal_conversion(TEXT, TEXT, INTEGER, TEXT, TIMESTAMPTZ);
CREATE OR REPLACE FUNCTION record_renewal_conversion(
  p_subscription_id TEXT, p_invoice_id TEXT, p_amount_cents INTEGER, p_currency TEXT, p_paid_at TIMESTAMPTZ,
  p_payment_intent TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_mem memberships%ROWTYPE;
  v_txn UUID;
BEGIN
  IF p_subscription_id IS NULL OR p_invoice_id IS NULL OR COALESCE(p_amount_cents, 0) <= 0 THEN RETURN NULL; END IF;
  SELECT * INTO v_mem FROM memberships WHERE stripe_subscription_id = p_subscription_id LIMIT 1;
  IF NOT FOUND THEN RETURN NULL; END IF;
  -- renew_membership_cycle() runs first and writes the renewal's transaction;
  -- keying the conversion to it lets a refund of that charge come off the
  -- report. Without a payment intent, fall back to the invoice id.
  IF p_payment_intent IS NOT NULL THEN
    SELECT id INTO v_txn FROM transactions
    WHERE stripe_payment_intent_id = p_payment_intent AND membership_id = v_mem.id LIMIT 1;
  END IF;
  RETURN record_conversion_or_queue(jsonb_build_object(
    'p_studio_id', v_mem.studio_id, 'p_profile_id', v_mem.profile_id, 'p_visitor_id', NULL,
    'p_conversion_type', 'membership_renewal', 'p_value_cents', p_amount_cents,
    'p_currency', upper(COALESCE(p_currency, 'USD')),
    -- A stable UUID per Stripe invoice id.
    'p_entity_type', CASE WHEN v_txn IS NULL THEN 'stripe_invoice' ELSE 'transaction' END,
    'p_entity_id', COALESCE(v_txn, md5('stripe:' || p_invoice_id)::uuid),
    'p_converting_session_id', NULL, 'p_member_source', NULL,
    'p_occurred_at', COALESCE(p_paid_at, NOW())));
END;
$$;
REVOKE ALL ON FUNCTION record_renewal_conversion(TEXT, TEXT, INTEGER, TEXT, TIMESTAMPTZ, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION record_renewal_conversion(TEXT, TEXT, INTEGER, TEXT, TIMESTAMPTZ, TEXT) TO service_role;

-- Internal helpers and trigger functions: never callable by clients.
REVOKE ALL ON FUNCTION booking_session_from_request(UUID, UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION record_member_booking_conversion() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION record_promoted_booking_conversion() FROM PUBLIC, anon, authenticated;

-- ===========================================================================
-- Acquisition dates (PR #72 review)
-- ===========================================================================
-- Existing members keep the date they joined; without this the first booking
-- after deploy would stamp them as acquired today. New rows stay NULL until
-- their first conversion (record_conversion() sets it), so a guest identity
-- created for an abandoned checkout is never counted as a new person.
UPDATE studio_members SET acquired_at = created_at WHERE acquired_at IS NULL;
-- Relationships that existed before this migration (including imports made
-- before import-members tagged them) were not acquired through anything this
-- report can see; mark them so "new people" counts only acquisitions since
-- tracking began. Runs once, at migration time; new rows keep NULL until a
-- conversion sets their real source.
UPDATE studio_members SET source = 'pre_tracking' WHERE source IS NULL;


-- ===========================================================================
-- The studio the caller administers (PR #72 review)
-- ===========================================================================
-- get_my_studio() returns the earliest assignment of any role. Owner/admin
-- screens (Automations, Where students come from) need a studio the caller
-- can actually manage: a teacher at studio A who owns studio B gets B here.
CREATE OR REPLACE FUNCTION get_my_admin_studio()
RETURNS TABLE (studio_id UUID, name TEXT, slug TEXT, currency TEXT, staff_role user_role)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT s.id, s.name, s.slug, s.currency, ss.role
  FROM studio_staff ss
  JOIN studios s ON s.id = ss.studio_id
  WHERE ss.profile_id = (SELECT auth.uid())
    AND ss.is_active = TRUE
    AND ss.role IN ('owner', 'admin')
  ORDER BY ss.created_at ASC
  LIMIT 1;
$$;
REVOKE ALL ON FUNCTION get_my_admin_studio() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION get_my_admin_studio() TO authenticated;

COMMIT;
